### ISSUE TITLE
Failed to resolve: de.uniluebeck.itm:ncoap-core:1.8.3-SNAPSHOT

### ISSUE THREAD

**Issue by SlimaneChen** [okleine/spitfirefox#1]
Hello! 
Thanks for built this at the first.

When i using the gradle sync, and it shows the error 
Error:(32, 13) Failed to resolve: de.uniluebeck.itm:ncoap-core:1.8.3-SNAPSHOT

But i dont know if i need to change the version or using other extra library?

Thanks!

**Comment by okleine** [comment]
The artifact could not be resolved because I simply forgot to deploy it on the server... I just caught up on that. Could you please check if the problem is gone now? Thank you!

**Comment by SlimaneChen** [comment]
Sorry I've tried again and it still doesn't work, the problem is the same.
Thanks for helping this, hope can make it work soon!

**Comment by okleine** [comment]
Apparently, I missed to configure our SNAPSHOT repository for the nCoap dependency in the "build.gradle". This is now also fixed. Please give it another try...

**Comment by SlimaneChen** [comment]
The problem solved! Thank you take time to do this!
