### ISSUE TITLE
Failed to resolve: de.uniluebeck.itm:ncoap-core:1.8.3-SNAPSHOT 

### ISSUE THREAD

**Issue by michan18** [okleine/spitfirefox#3]
I am getting error Failed to resolve: de.uniluebeck.itm:ncoap-core:1.8.3-SNAPSHOT , is this missing from repo?

**Comment by okleine** [comment]
There is not a single reason but a combination of two:

1. The group ID of the dependency was changed to "de.uzl.itm" a long time ago. Apparently, you are not using the latest version. 

2. Recently, there was a software update on the server that hosts the Maven artifact. During the update they changed the repository URLs. I just updated the "build.gradle" according to the new server setup.

Now, I was able to build and run the app.

**Comment by michan18** [comment]
It worked.. Thank you.....
